### ISSUE TITLE
Improve and seperate LIC1 logic

### ISSUE THREAD

**Issue by MrLarssonJr** [DD2480-Project-group-25/DECIDE#48]
Checking if three points " cannot all be contained within or on a circle of radius RADIUS1. (0 ≤ RADIUS1)." is common between LICs and should be extracted.

Also the logic used now is missing some edge cases.

**Comment by MrLarssonJr** [comment]
I've found this paper: 
[a463920.pdf](https://github.com/DD2480-Project-group-25/DECIDE/files/2799217/a463920.pdf)
It describes how one can calculate the area of the common intersection of three circles.

If one imagines three circles with radius RADIUS1 around the three points, the common overlap would be where one could place a circle, also with radius RADIUS1, that would contain the three points. So if the area of this common overlap exists, the criterion we are looking for is false.

**Comment by vronc** [comment]
This issue is divided into two new issues; #52 and #53
